name: NG5 Configuration Example
machine_name: ng5-example-configuration
type: pdb
description: 'NG 5 Example Component Configuration'
package: NG5
version: '1.0.0'
core: '8.x'
module_status: active
presentation: ng5
configuration:
  text:
    type: textfield
    title: 'What do you want to say?'
    default_value: 'Hello world!'
